services:
  - type: web
    name: youtube-trending-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
